### PR TITLE
[Feature] Theme Support (and better UI)

### PR DESCRIPTION
**Pull request by seshrs**
Given that we've already created a wrapper for displaying the spec, I think theme support is the next logical step! This PR has a lot of changes — for the subthemes to be written efficiently, I needed to change how the code was organized. The code is now better organized and documented than before, so hopefully maintenance will be a bit easier.

_Tl;dr: See the live demo at http://www-personal.umich.edu/~seshrs/primer-spec-develop/. Then see the **"Maintenance notes and questions"** section at the end of this note._

## Summary
- Modified visual appearance of sidebar:
  - Sidebar is wider with larger text.
  - Sidebar toggle button now uses the recognizable "hamburger" icon.
  - Highlighted section in the sidebar is the section at the top of the viewer's screen. (Previously, it was whatever section that was above the middle of the screen.)
  - JavaScript code to generate the sidebar's table of contents now groups headings into "sections". (The new subthemes rely on this grouping to better style the sidebar.)
- Better mobile experience:
  - A "topbar" holds the sidebar-toggling button.
  - Clicking a link in the sidebar closes the sidebar.
- **SUBTHEME SUPPORT!**
  - Modified structure of stylesheets in `_sass/spec` to make it relatively easier to create new subthemes.
  - Added 3 new subtheme stylesheets: *bella*, *modern* and *xcode-dark*.
  - Added a "settings pane" in `_layouts/spec.html`. A dropdown menu allows viewers to choose a subtheme to use. (The settings pane, like the sidebar, does not show up when the webpage is printed.)
- Organized HTML and JavaScript code in `_layouts/spec.html` a little better:
  - Added comments, divided the script code into sections.
  - Made use of built-in GitHub Primer style classes.
  - Added a JQuery optimization to run the "selectors" (to find matching HTML elements) only once on page-load. This improves page performance.
- Made it easier to merge changes from up-stream by moving all Primer Spec modifications to new files.
- Updated README with instructions on adding subthemes.

### Live Demo
A live demo of the features described in this PR is available at http://www-personal.umich.edu/~seshrs/primer-spec-develop/.

## Validation
Please verify the visual appearance of the subthemes (including *default*) on your desktop/laptop/mobile device. Please play around with the sidebar toggles and the settings pane to ensure that they work as expected on your devices.

## Maintenance notes and questions
_CC: @awdeorio, @amirkamil_, @jamesjuett

Hopefully, the code is now a little better structured and documented with comments. As noted in the README, this repository needs to be [kept up-to-date with the upstream](https://github.com/eecs485staff/primer-spec#keeping-this-theme-up-to-date-with-primer) — this should be relatively easier after this PR is merged because all changes from upstream are contained in new external files.

In the unlikely event that problems occur and the spec does not render, simply update the project spec markdown file to use `layout: default` instead of `layout: spec` to use GitHub's default theme (without the sidebar.)

I wanted to discuss two options for deploying this PR (especially since changes to this repo affect EECS 485, EECS 280 and, potentially, EECS 490):

- Merge this PR with `master`. This is easier to maintain because we only maintain one branch. However, project specs from all these courses will begin using these new features when their websites are re-deployed. (Maybe this is not an issue given that project specs can revert to the default GitHub theme by using `layout: default`?)
- Maintain this subtheme feature in a separate branch, and require project specs to opt-in to showing subthemes. The opt-in would have to be done in the `_config.yml` file in each project repo. I personally think this is harder to maintain since we would have to support both the old style and the new style.

What do you think?

---

_Bella Kim (@bellakiminsun) suggested the idea of spec themes, designed the themes and provided usability feedback._

### CODE REVIEW

**Comment by amirkamil** [comment]
I would go with the easier-to-maintain option.

Amir

**Comment by awdeorio** [comment]
I agree with the easy-to-maintain option.

**Comment by awdeorio** [comment]
It seems like I'm still seeing the old version on EECS 485 P1:
Screen Shot 2019-04-29 at 8 35 44 AM

**Comment by seshrs** [comment]
You’ll have to push a commit (at least an empty commit) to the P1 repo to trigger re-deployment of GitHub pages.

**Pull request merged**
